version: "3.9"
services:
  web:
    depends_on:
      - postgres_db
    build:
      context: ./src
      dockerfile: Dockerfile.local
    image: python-flashcards-local:v1
    env_file:
      - src/.env
    ports:
      - "8000:8000"
    volumes:
      - ./src/:/app/
    command: sh -c "chmod +x /app/migrate.sh &&
                    sh /app/migrate.sh &&
                    /opt/venv/bin/uvicorn --reload main:app --host 0.0.0.0 --port 8000"
  postgres_db:
    image: postgres
    command: -p 5434
    env_file:
      - src/.env
    expose:
      - 5434
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: