"""Add Flashcard and Collection relationship

Revision ID: 5975e4c6a906
Revises: acf3d8f1ab3a
Create Date: 2023-05-26 15:43:37.964551

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "5975e4c6a906"
down_revision = "acf3d8f1ab3a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topic",
        sa.Column(
            "id", sa.Integer(), sa.Identity(always=False, cycle=True), nullable=False
        ),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "collection",
        sa.Column(
            "id", sa.Integer(), sa.Identity(always=False, cycle=True), nullable=False
        ),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column("topic_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topic.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "collection_flashcards",
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("flashcard_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["flashcard_id"],
            ["flashcard.id"],
        ),
        sa.PrimaryKeyConstraint("collection_id", "flashcard_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("collection_flashcards")
    op.drop_table("collection")
    op.drop_table("topic")
    # ### end Alembic commands ###
