"""Add relationship with user and flashcard

Revision ID: acf3d8f1ab3a
Revises: 9d3ed2eb8afa
Create Date: 2023-05-15 14:47:40.290627

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "acf3d8f1ab3a"
down_revision = "9d3ed2eb8afa"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("flashcard", sa.Column("creator_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "flashcard", "user", ["creator_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "flashcard", type_="foreignkey")
    op.drop_column("flashcard", "creator_id")
    # ### end Alembic commands ###
