"""Add Flashcard table

Revision ID: d599fbc7343a
Revises: 
Create Date: 2023-05-09 13:08:25.776284

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d599fbc7343a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flashcard",
        sa.Column(
            "id", sa.Integer(), sa.Identity(always=False, cycle=True), nullable=False
        ),
        sa.Column("question", sa.String(), nullable=True),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("flashcard")
    # ### end Alembic commands ###
