"""Add Flashcard and Tag many to many relationship

Revision ID: 841ed3b77b2c
Revises: e73a9aa3dbbc
Create Date: 2023-05-10 16:04:29.411554

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "841ed3b77b2c"
down_revision = "e73a9aa3dbbc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "flashcard_tags",
        sa.Column("flashcard_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["flashcard_id"],
            ["flashcard.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tag.id"],
        ),
        sa.PrimaryKeyConstraint("flashcard_id", "tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("flashcard_tags")
    # ### end Alembic commands ###
