"""Update User table

Revision ID: 39c664886f9b
Revises: 5975e4c6a906
Create Date: 2023-05-26 15:46:19.863312

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "39c664886f9b"
down_revision = "5975e4c6a906"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
