"""Add table Tag

Revision ID: e73a9aa3dbbc
Revises: d599fbc7343a
Create Date: 2023-05-10 15:19:00.686674

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e73a9aa3dbbc"
down_revision = "d599fbc7343a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column(
            "id", sa.Integer(), sa.Identity(always=False, cycle=True), nullable=False
        ),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tag")
    # ### end Alembic commands ###
