"""Add column date_joined to user table

Revision ID: 9d3ed2eb8afa
Revises: 507650b8c0ac
Create Date: 2023-05-14 15:50:12.192109

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "9d3ed2eb8afa"
down_revision = "507650b8c0ac"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("date_joined", sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "date_joined")
    # ### end Alembic commands ###
