"""Update Topic table

Revision ID: 22ad575f338f
Revises: 39c664886f9b
Create Date: 2023-05-26 15:47:39.759363

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "22ad575f338f"
down_revision = "39c664886f9b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
